Aim Trainer
sree-hari-s/MasteringPyTrail pull request #33
Opened 2023-10-06 12:47 UTC by avimoti1234

If there is anything you want, let me know

2023-10-06 17:45 UTC, sree-hari-s commented
very nicely done can you please include a readme file just containing a brief description of your work 

and I have created a dedicated directory for tkinter projects so you can change you file location also.

2023-10-06 19:22 UTC, avimoti1234 commented
Hey, 
I have done all that:)
Would be glad if you merge it.

2023-10-06 19:29 UTC, avimoti1234 commented
I've deleted some .xml files that I accidentally pushed

2023-10-07 21:35 UTC, avimoti1234 commented
And add the hacktoberfest label:)

2023-10-08 00:07 UTC, sree-hari-s commented on Projects/Tkinter-Projects/Aim Trainer/README.md
> +   cd Aim Trainer
everyone seems to be copy-pasting previous work, isn't it?

2023-10-08 00:10 UTC, sree-hari-s commented on Projects/Tkinter-Projects/Aim Trainer/requirements.txt
> +tkinter
both are in-buit packages

2023-10-08 00:15 UTC, sree-hari-s approved these changes

2023-10-08 00:20 UTC, sree-hari-s requested changes
You seem to have changed a lot of file please remove those changes.

2023-10-08 14:58 UTC, avimoti1234 commented
I have only changed the file's day number because before you told me to move the project to the Tkinter folder it was located in the intermediate folder with the day number so I had to decrement all of the files day number

2023-10-08 15:20 UTC, sree-hari-s commented
> I have only changed the file's day number because before you told me to move the project to the Tkinter folder it was located in the intermediate folder with the day number so I had to decrement all of the files day number

You didn't pull the latest changes that's why it happened

2023-10-08 15:22 UTC, avimoti1234 commented
I have just done that again and I don't recognize any difference.
Can you explain me because everything looks fine to me

2023-10-08 15:24 UTC, sree-hari-s commented
I had changed few folders to here and there so your PR has 51 changed files so a conflict is happening

2023-10-08 15:29 UTC, avimoti1234 reviewed
Is that ok?

2023-10-08 15:54 UTC, avimoti1234 commented
How can I solve it?

2023-10-08 17:42 UTC, sree-hari-s commented
It would be better if you pull the latest  code and raise a PR again.

2023-10-08 17:42 UTC, closed without merging