added the two projects newly and updated the readme
sree-hari-s/MasteringPyTrail pull request #53
Opened 2023-10-12 06:26 UTC by seabeePraveen

After considering the checks so i have removed the secret key values form the project and made this new PR

2023-10-12 06:44 UTC, sree-hari-s commented on Projects/Django-Projects/EduFlow/README.md
> +## Getting Started
modify getting started for better understanding

2023-10-12 06:48 UTC, sree-hari-s commented
create a file `.env_sample` and create a sample of the original .env file.

and modify the instructions in the `Readme.md` for Eduflow

2023-10-12 06:50 UTC, sree-hari-s commented
In todolist `requirements.txt` `Readme.md` file missing

2023-10-12 06:50 UTC, seabeePraveen commented
yeah okay for the sample did u mean
.env_sample
SECRET_KEY = <your_key>

like this??

2023-10-12 06:50 UTC, sree-hari-s requested changes
Please make the modifications.

2023-10-12 06:51 UTC, sree-hari-s commented
> yeah okay for the sample did u mean .env_sample SECRET_KEY = <your_key>
> 
> like this??

Yeah just like that also add that in an instruction as it was not specified there.

2023-10-13 13:00 UTC, seabeePraveen commented
hello @sree-hari-s please once review this and let me know
Thank you!

2023-10-13 14:10 UTC, sree-hari-s commented
> hello @sree-hari-s please once review this and let me know Thank you!

Eduflow is working fine 

![image](https://github.com/sree-hari-s/MasteringPyTrail/assets/48482060/64451851-36db-4a53-b0b3-b94a8f237457)

it would be better if you could resolve blank tasks and also edit tasks would be a nice feature.

2023-10-13 14:13 UTC, seabeePraveen commented
yeah okay u just want me to undo the those empty tasks right? like it shouldn't take the input task as input and add into database right?

2023-10-13 14:14 UTC, sree-hari-s commented
> yeah okay u just want me to undo the those empty tasks right? like it shouldn't take the input task as input and add into database right?

empty input should not be accepted that's all.

2023-10-13 14:28 UTC, seabeePraveen commented
okay

On Fri, 13 Oct 2023 at 7:44 PM, SREEHARI S ***@***.***> wrote:

> yeah okay u just want me to undo the those empty tasks right? like it
> shouldn't take the input task as input and add into database right?
>
> empty input should not be accepted that's all.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sree-hari-s/MasteringPyTrail/pull/53#issuecomment-1761595460>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVFU5TQRHPW2VHFRBVQHWALX7FEETAVCNFSM6AAAAAA55CYAWKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRRGU4TKNBWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-03 17:27 UTC, merged