Solved aVeryBigSum.py problem
sree-hari-s/MasteringPyTrail pull request #57
Opened 2023-10-22 09:44 UTC by Souradeephazra123

## Fixes Issue

Closes  #56

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] I have updated the documentation accordingly.
- [ ] I have added a new Project.
- [ ] I have added a README.md file for the Project.
- [] The title of my pull request is a short description of the requested changes.

## Screenshots

<img width="944" alt="Screenshot 2023-10-22 150816" src="https://github.com/sree-hari-s/MasteringPyTrail/assets/105676331/00d6b50b-4bbd-469d-b0f3-1ec658fd5e6a">

2023-10-22 09:46 UTC, Souradeephazra123 commented
I have solved the problem in  #56.Please check it , and if it is correct then merge it.

2023-10-22 11:34 UTC, Souradeephazra123 commented
I have also added the Expense tracker in Project. Please review both of these and merge them.

2023-10-23 04:17 UTC, sree-hari-s commented
> I have also added the Expense tracker in Project. Please review both of these and merge them.

venv file not required please remove that from the expense tracker project.

2023-10-23 04:20 UTC, sree-hari-s commented
> I have also added the Expense tracker in Project. Please review both of these and merge them.

Also, there is a separate directory for flask projects

2023-10-23 12:44 UTC, Souradeephazra123 commented
please add the hacktoberfest-accepted lebel in this problem.

2023-10-24 07:03 UTC, sree-hari-s commented
![image](https://github.com/sree-hari-s/MasteringPyTrail/assets/48482060/1c33cfde-b212-45d3-b65b-75ac4c713237)

Instruction to run the application is not clear. Not able to start you application.

2023-10-24 07:04 UTC, sree-hari-s requested changes

2023-10-24 07:04 UTC, sree-hari-s commented on Projects/Flask-Projects/expense_tracker/readme.md
> +3. Run the application: `python run.py`
Error while following the installation instruction.

2023-11-25 18:02 UTC, merged