adding Pizza truck simulator as a pygame project
sree-hari-s/MasteringPyTrail pull request #59
Opened 2023-10-23 14:45 UTC by TIDYMOUSE

- [x] I have updated the documentation accordingly.
- [x] I have added a new Project.
- [x] I have added a README.md file for the Project.
- [x] The title of my pull request is a short description of the requested changes.

2023-10-23 14:47 UTC, TIDYMOUSE commented
Hello @sree-hari-s please review my project.  This is one my initial project that I created after learning pygame. Also one of the used song is copy righted, should I change it or is it fine?

2023-10-23 14:48 UTC, TIDYMOUSE commented
Also it would be great if you added hacktober fest accepted as labels and assign yourself as the reviewer
@sree-hari-s

2023-10-24 07:08 UTC, sree-hari-s commented
> Hello @sree-hari-s please review my project. This is one my initial project that I created after learning pygame. Also one of the used song is copy righted, should I change it or is it fine?

It would be better to change that song.

2023-10-24 07:09 UTC, sree-hari-s requested changes

2023-10-24 07:09 UTC, sree-hari-s commented on Projects/Pygame-Projects/Pizza Delivery Truck Simulator/README.md
Also just add an information that space button is for jumping. and requirements.txt would also be good addition in the directory.

2023-10-24 09:17 UTC, TIDYMOUSE commented on Projects/Pygame-Projects/Pizza Delivery Truck Simulator/README.md
@sree-hari-s Ive made the required changes 
- [x] added requirements.md
- [x] Used non-copyrighted and royalty free music and images.

If you want some more improvements, please contact me. Thank You.

2023-10-24 09:24 UTC, sree-hari-s approved these changes

2023-10-24 09:25 UTC, merged

2023-10-24 09:26 UTC, sree-hari-s commented
Thankyou for your contribution. Please 🌟 the repo and try to contribute more works.